[package]
name = "rust_prime_finder"
version = "0.1.0"
authors = ["Alain Hardy <alain.hardy@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
